lazyWarlockLoad.metadata:updateRevisionFromKeyword("$Revision: 534 $")

function lazyWarlockLoad.LoadWarlockLocalization(locale)
	
	lazyWarlockLocale.enUS.ACTION_TTS.amplifyCurse        = "Amplify Curse"
	lazyWarlockLocale.enUS.ACTION_TTS.banish              = "Banish"
	lazyWarlockLocale.enUS.ACTION_TTS.conflagrate         = "Conflagrate"
	lazyWarlockLocale.enUS.ACTION_TTS.corruption          = "Corruption"
	
	lazyWarlockLocale.enUS.ACTION_TTS.createFire          = "Create Firestone"
	lazyWarlockLocale.enUS.ACTION_TTS.createGreaterFire   = "Create Firestone (Greater)"
	lazyWarlockLocale.enUS.ACTION_TTS.createLesserFire    = "Create Firestone (Lesser)"
	lazyWarlockLocale.enUS.ACTION_TTS.createMajorFire     = "Create Firestone (Major)"
	
	lazyWarlockLocale.enUS.ACTION_TTS.createGreaterHealth = "Create Healthstone (Greater)"
	lazyWarlockLocale.enUS.ACTION_TTS.createHealth        = "Create Healthstone"
	lazyWarlockLocale.enUS.ACTION_TTS.createLesserHealth  = "Create Healthstone (Lesser)"
	lazyWarlockLocale.enUS.ACTION_TTS.createMajorHealth   = "Create Healthstone (Major)"
	lazyWarlockLocale.enUS.ACTION_TTS.createMinorHealth   = "Create Healthstone (Minor)"
	
	lazyWarlockLocale.enUS.ACTION_TTS.createGreaterSoul   = "Create Soulstone (Greater)"
	lazyWarlockLocale.enUS.ACTION_TTS.createLesserSoul    = "Create Soulstone (Lesser)"
	lazyWarlockLocale.enUS.ACTION_TTS.createMajorSoul     = "Create Soulstone (Major)"
	lazyWarlockLocale.enUS.ACTION_TTS.createMinorSoul     = "Create Soulstone (Minor)"
	lazyWarlockLocale.enUS.ACTION_TTS.createSoul          = "Create Soulstone"
	
	lazyWarlockLocale.enUS.ACTION_TTS.createGreaterSpell  = "Create Spellstone (Greater)"
	lazyWarlockLocale.enUS.ACTION_TTS.createMajorSpell    = "Create Spellstone (Major)"
	lazyWarlockLocale.enUS.ACTION_TTS.createSpell         = "Create Spellstone"
	
	lazyWarlockLocale.enUS.ACTION_TTS.curseAgony          = "Curse of Agony"
	lazyWarlockLocale.enUS.ACTION_TTS.curseDoom           = "Curse of Doom"
	lazyWarlockLocale.enUS.ACTION_TTS.curseElements       = "Curse of Elements"
	lazyWarlockLocale.enUS.ACTION_TTS.curseExhaustion     = "Curse of Exhaustion"
	lazyWarlockLocale.enUS.ACTION_TTS.curseReckless       = "Curse of Recklessness"
	lazyWarlockLocale.enUS.ACTION_TTS.curseShadow         = "Curse of Shadow"
	lazyWarlockLocale.enUS.ACTION_TTS.curseTongues        = "Curse of Tongues"
	lazyWarlockLocale.enUS.ACTION_TTS.curseWeakness       = "Curse of Weakness"
	lazyWarlockLocale.enUS.ACTION_TTS.darkPact            = "Dark Pact"
	lazyWarlockLocale.enUS.ACTION_TTS.deathCoil           = "Death Coil"
	lazyWarlockLocale.enUS.ACTION_TTS.demonArmor          = "Demon Armor"
	lazyWarlockLocale.enUS.ACTION_TTS.demonSacrifice      = "Demon Sacrifice"
	lazyWarlockLocale.enUS.ACTION_TTS.demonSkin           = "Demon Skin"
	lazyWarlockLocale.enUS.ACTION_TTS.detectGreaterInvis  = "Detect Greater Invisibility"
	lazyWarlockLocale.enUS.ACTION_TTS.detectInvis         = "Detect Invisibility"
	lazyWarlockLocale.enUS.ACTION_TTS.detectLesserInvis   = "Detect Lesser Invisibility"
	lazyWarlockLocale.enUS.ACTION_TTS.drainLife           = "Drain Life"
	lazyWarlockLocale.enUS.ACTION_TTS.drainMana           = "Drain Mana"
	lazyWarlockLocale.enUS.ACTION_TTS.drainSoul           = "Drain Soul"
	lazyWarlockLocale.enUS.ACTION_TTS.enslave             = "Enslave Demon"
	lazyWarlockLocale.enUS.ACTION_TTS.fear                = "Fear"
	lazyWarlockLocale.enUS.ACTION_TTS.felDomination       = "Fel Domination"
	lazyWarlockLocale.enUS.ACTION_TTS.funnel              = "Health Funnel"
	lazyWarlockLocale.enUS.ACTION_TTS.hellfire            = "Hellfire"
	lazyWarlockLocale.enUS.ACTION_TTS.howl                = "Howl of Terror"
	lazyWarlockLocale.enUS.ACTION_TTS.immolate            = "Immolate"
	lazyWarlockLocale.enUS.ACTION_TTS.inferno	          = "Inferno"
	lazyWarlockLocale.enUS.ACTION_TTS.lifeTap             = "Life Tap"
	lazyWarlockLocale.enUS.ACTION_TTS.pact                = "Dark Pact"
	lazyWarlockLocale.enUS.ACTION_TTS.pain                = "Searing Pain"
	lazyWarlockLocale.enUS.ACTION_TTS.rainFire            = "Rain of Fire"
	lazyWarlockLocale.enUS.ACTION_TTS.senseDemons         = "Sense Demons"
	lazyWarlockLocale.enUS.ACTION_TTS.shadowBolt          = "Shadow Bolt"
	lazyWarlockLocale.enUS.ACTION_TTS.shadowburn          = "Shadowburn"
	lazyWarlockLocale.enUS.ACTION_TTS.shadowWard          = "Shadow Ward"
	lazyWarlockLocale.enUS.ACTION_TTS.siphon              = "Siphon Life"
	lazyWarlockLocale.enUS.ACTION_TTS.soulFire            = "Soul Fire"
	lazyWarlockLocale.enUS.ACTION_TTS.soulLink            = "Soul Link"
	lazyWarlockLocale.enUS.ACTION_TTS.summonDread         = "Summon Dreadsteed"
	lazyWarlockLocale.enUS.ACTION_TTS.spellLock           = "Spell lock"
	lazyWarlockLocale.enUS.ACTION_TTS.summonFel           = "Summon Felhunter"
	lazyWarlockLocale.enUS.ACTION_TTS.summonImp           = "Summon Imp"
	lazyWarlockLocale.enUS.ACTION_TTS.summonSteed         = "Summon Felsteed"
	lazyWarlockLocale.enUS.ACTION_TTS.summonSuc           = "Summon Succubus"
	lazyWarlockLocale.enUS.ACTION_TTS.summonVW            = "Summon Voidwalker"
	
	lazyWarlockLocale.enUS.ACTION_TTS.bloodPact           = "Blood Pact"
	lazyWarlockLocale.enUS.ACTION_TTS.firebolt            = "Firebolt"
	lazyWarlockLocale.enUS.ACTION_TTS.phaseShift          = "Phase Shift"
	lazyWarlockLocale.enUS.ACTION_TTS.fireShield          = "Fire Shield"
	
	lazyWarlockLocale.enUS.ACTION_TTS.consumeShadows      = "Consume Shadows"
	lazyWarlockLocale.enUS.ACTION_TTS.sacrifice           = "Sacrifice"
	lazyWarlockLocale.enUS.ACTION_TTS.suffering           = "Suffering"
	lazyWarlockLocale.enUS.ACTION_TTS.torment             = "Torment"
	
	lazyWarlockLocale.enUS.ACTION_TTS.lashPain            = "Lash of Pain"
	lazyWarlockLocale.enUS.ACTION_TTS.lesserInvisibility  = "Lesser Invisibility"
	lazyWarlockLocale.enUS.ACTION_TTS.seduction           = "Seduction"
	lazyWarlockLocale.enUS.ACTION_TTS.soothingKiss        = "Soothing Kiss"
	
	lazyWarlockLocale.enUS.ACTION_TTS.taintedBlood        = "Tainted Blood"
	lazyWarlockLocale.enUS.ACTION_TTS.spellLock           = "Spell Lock"
	lazyWarlockLocale.enUS.ACTION_TTS.devourMagic         = "Devour Magic"
	lazyWarlockLocale.enUS.ACTION_TTS.paranoia            = "Paranoia"
	
	lazyWarlockLocale.enUS.HEALTHSTONE                    = "Healthstone"
	lazyWarlockLocale.enUS.SOULSTONE                      = "Soulstone"
	lazyWarlockLocale.enUS.FIRESTONE                      = "Firestone"
	
	-- LazyWarlock.lua
	WARLOCK_ADDON_LOADED = " loaded. Powered by "
	
	-- ParseWarlock.lua
	WARLOCK_RANK = "Rank "
	WARLOCK_CONFLAG_NOT_SUPPORT = " of Conflagrate is not supported by LazyScript! Please report this error to the lazydevs team."
	WARLOCK_CONFLAG_DAMAGE = "IsLastConflagrateChance: Conflagrate damage="
	WARLOCK_OFFHAND_CONTAINS = "Offhand contains: "
	
	
	function lazyWarlock.CustomLocaleHelp() return [[<H2>Warlock Criteria:</H2>]] end
	
	if (locale == "ruRU") then
	
		lazyWarlockLocale.ruRU.ACTION_TTS.amplifyCurse        = "Усиление проклятия"
		lazyWarlockLocale.ruRU.ACTION_TTS.banish              = "Изгнание"
		lazyWarlockLocale.ruRU.ACTION_TTS.conflagrate         = "Поджигание"
		lazyWarlockLocale.ruRU.ACTION_TTS.corruption          = "Порча"
		
		lazyWarlockLocale.ruRU.ACTION_TTS.createFire          = "Создание камня огня"
		lazyWarlockLocale.ruRU.ACTION_TTS.createGreaterFire   = "Создание камня огня (большого)"
		lazyWarlockLocale.ruRU.ACTION_TTS.createLesserFire    = "Создание камня огня (малого)"
		lazyWarlockLocale.ruRU.ACTION_TTS.createMajorFire     = "Создание камня огня (крупного)"
		
		lazyWarlockLocale.ruRU.ACTION_TTS.createGreaterHealth = "Создание камня здоровья (большого)"
		lazyWarlockLocale.ruRU.ACTION_TTS.createHealth        = "Создание камня здоровья"
		lazyWarlockLocale.ruRU.ACTION_TTS.createLesserHealth  = "Создание камня здоровья (малого)"
		lazyWarlockLocale.ruRU.ACTION_TTS.createMajorHealth   = "Создание камня здоровья (крупного)"
		lazyWarlockLocale.ruRU.ACTION_TTS.createMinorHealth   = "Создание камня здоровья (крошечного)"
		
		lazyWarlockLocale.ruRU.ACTION_TTS.createGreaterSoul   = "Создание камня души (большого)"
		lazyWarlockLocale.ruRU.ACTION_TTS.createLesserSoul    = "Создание камня души (малого)"
		lazyWarlockLocale.ruRU.ACTION_TTS.createMajorSoul     = "Создание камня души (крупного)"
		lazyWarlockLocale.ruRU.ACTION_TTS.createMinorSoul     = "Создание камня души (крошечного)"
		lazyWarlockLocale.ruRU.ACTION_TTS.createSoul          = "Создание камня души"
		
		lazyWarlockLocale.ruRU.ACTION_TTS.createGreaterSpell  = "Создание камня чар (большого)"
		lazyWarlockLocale.ruRU.ACTION_TTS.createMajorSpell    = "Создание камня чар (крупного)"
		lazyWarlockLocale.ruRU.ACTION_TTS.createSpell         = "Создание камня чар"
		
		lazyWarlockLocale.ruRU.ACTION_TTS.curseAgony          = "Проклятие агонии"
		lazyWarlockLocale.ruRU.ACTION_TTS.curseDoom           = "Проклятие рока"
		lazyWarlockLocale.ruRU.ACTION_TTS.curseElements       = "Проклятие стихий"
		lazyWarlockLocale.ruRU.ACTION_TTS.curseExhaustion     = "Проклятие изнеможения"
		lazyWarlockLocale.ruRU.ACTION_TTS.curseReckless       = "Проклятие безрассудства"
		lazyWarlockLocale.ruRU.ACTION_TTS.curseShadow         = "Проклятие Тьмы"
		lazyWarlockLocale.ruRU.ACTION_TTS.curseTongues        = "Проклятие косноязычия"
		lazyWarlockLocale.ruRU.ACTION_TTS.curseWeakness       = "Проклятие слабости"
		lazyWarlockLocale.ruRU.ACTION_TTS.darkPact            = "Темный союз"
		lazyWarlockLocale.ruRU.ACTION_TTS.deathCoil           = "Лик смерти"
		lazyWarlockLocale.ruRU.ACTION_TTS.demonArmor          = "Демонический доспех"
		lazyWarlockLocale.ruRU.ACTION_TTS.demonicSacrifice    = "Демоническое жертвоприношение"
		lazyWarlockLocale.ruRU.ACTION_TTS.demonSkin           = "Шкура демона"
		lazyWarlockLocale.ruRU.ACTION_TTS.detectGreaterInvis  = "Обнаружение большой невидимости"
		lazyWarlockLocale.ruRU.ACTION_TTS.detectInvis         = "Обнаружение невидимости"
		lazyWarlockLocale.ruRU.ACTION_TTS.detectLesserInvis   = "Обнаружение простой невидимости"
		lazyWarlockLocale.ruRU.ACTION_TTS.drainLife           = "Похищение жизни"
		lazyWarlockLocale.ruRU.ACTION_TTS.drainMana           = "Похищение маны"
		lazyWarlockLocale.ruRU.ACTION_TTS.drainSoul           = "Похищение души"
		lazyWarlockLocale.ruRU.ACTION_TTS.enslave             = "Порабощение демона"
		lazyWarlockLocale.ruRU.ACTION_TTS.fear                = "Страх"
		lazyWarlockLocale.ruRU.ACTION_TTS.felDomination       = "Господство Скверны"
		lazyWarlockLocale.ruRU.ACTION_TTS.funnel              = "Канал здоровья"
		lazyWarlockLocale.ruRU.ACTION_TTS.hellfire            = "Адское Пламя"
		lazyWarlockLocale.ruRU.ACTION_TTS.howl                = "Вой ужаса"
		lazyWarlockLocale.ruRU.ACTION_TTS.immolate            = "Жертвенный огонь"
		lazyWarlockLocale.ruRU.ACTION_TTS.inferno     		  = "Инфернал"
		lazyWarlockLocale.ruRU.ACTION_TTS.lifeTap             = "Жизнеотвод"
		lazyWarlockLocale.ruRU.ACTION_TTS.pain                = "Жгучая боль"
		lazyWarlockLocale.ruRU.ACTION_TTS.rainFire            = "Огненный ливень"
		lazyWarlockLocale.ruRU.ACTION_TTS.senseDemons         = "Чутье на демонов"
		lazyWarlockLocale.ruRU.ACTION_TTS.shadowBolt          = "Стрела Тьмы"
		lazyWarlockLocale.ruRU.ACTION_TTS.shadowburn          = "Ожог Тьмы"
		lazyWarlockLocale.ruRU.ACTION_TTS.shadowWard          = "Защита от темной магии"
		lazyWarlockLocale.ruRU.ACTION_TTS.siphon              = "Вытягивание жизни"
		lazyWarlockLocale.ruRU.ACTION_TTS.soulFire            = "Ожог души"
		lazyWarlockLocale.ruRU.ACTION_TTS.soulLink            = "Связка души"
		lazyWarlockLocale.ruRU.ACTION_TTS.summonDread         = "Призыв коня погибели"
		lazyWarlockLocale.ruRU.ACTION_TTS.summonImp           = "Призыв беса"
		lazyWarlockLocale.ruRU.ACTION_TTS.summonFel           = "Призыв охотника Скверны"
		lazyWarlockLocale.ruRU.ACTION_TTS.summonSteed         = "Призывание коня Скверны"
		lazyWarlockLocale.ruRU.ACTION_TTS.summonSuc           = "Призыв суккуба"
		lazyWarlockLocale.ruRU.ACTION_TTS.summonVW            = "Призыв демона Бездны"
		
		lazyWarlockLocale.ruRU.ACTION_TTS.bloodPact           = "Кровавый союз"
		lazyWarlockLocale.ruRU.ACTION_TTS.firebolt            = "Огненная стрела"
		lazyWarlockLocale.ruRU.ACTION_TTS.phaseShift          = "Бегство в астрал"
		lazyWarlockLocale.ruRU.ACTION_TTS.fireShield          = "Огненный щит"
		
		lazyWarlockLocale.ruRU.ACTION_TTS.consumeShadows      = "Поглощение теней"
		lazyWarlockLocale.ruRU.ACTION_TTS.sacrifice           = "Жертвоприношение"
		lazyWarlockLocale.ruRU.ACTION_TTS.suffering           = "Муки"
		lazyWarlockLocale.ruRU.ACTION_TTS.torment             = "Мучение"
		
		lazyWarlockLocale.ruRU.ACTION_TTS.lashPain            = "Всплеск боли"
		lazyWarlockLocale.ruRU.ACTION_TTS.lesserInvisibility  = "Простая невидимость"
		lazyWarlockLocale.ruRU.ACTION_TTS.seduction           = "Соблазн"
		lazyWarlockLocale.ruRU.ACTION_TTS.soothingKiss        = "Успокаивающий поцелуй"
		
		lazyWarlockLocale.ruRU.ACTION_TTS.taintedBlood        = "Порченая кровь"
		lazyWarlockLocale.ruRU.ACTION_TTS.spellLock           = "Запрет чар"
		lazyWarlockLocale.ruRU.ACTION_TTS.devourMagic         = "Пожирание магии"
		lazyWarlockLocale.ruRU.ACTION_TTS.paranoia            = "Паранойя"
		
		lazyWarlockLocale.ruRU.HEALTHSTONE                    = "Камень здоровья"
		lazyWarlockLocale.ruRU.SOULSTONE                      = "Осколок души"
		lazyWarlockLocale.ruRU.FIRESTONE                      = "Камень огня"
		
		-- LazyWarlock.lua
		WARLOCK_ADDON_LOADED = " загружен. Работает от "
		
		-- ParseWarlock.lua
		WARLOCK_RANK = "Уровень "
		WARLOCK_CONFLAG_NOT_SUPPORT = " Поджигания не поддерживается LazyScript! Пожалуйста, сообщите об этой ошибке команде lazydevs."
		WARLOCK_CONFLAG_DAMAGE = "IsLastConflagrateChance: Урон Поджигания="
		WARLOCK_OFFHAND_CONTAINS = "Левая рука содержит: "
	
		function lazyWarlock.CustomLocaleHelp() return [[<H2>Критерии Чернокнижника:</H2>]] end
		
		elseif (locale == "deDE") then
		
		lazyWarlockLocale.deDE.ACTION_TTS.consumeShadows      = "Schatten verzehren"
		lazyWarlockLocale.deDE.ACTION_TTS.curseDoom           = "Fluch der Verdammnis'-Effekt"
		lazyWarlockLocale.deDE.ACTION_TTS.curseReckless       = "Fluch der Tollk\195\188hnheit"
		lazyWarlockLocale.deDE.ACTION_TTS.demonArmor          = "D\195\164monenr\195\188stung"
		lazyWarlockLocale.deDE.ACTION_TTS.demonSkin           = "D\195\164monenhaut"
		lazyWarlockLocale.deDE.ACTION_TTS.detectGreaterInvis  = "Gro\195\159e Unsichtbarkeit entdecken"
		lazyWarlockLocale.deDE.ACTION_TTS.detectInvis         = "Unsichtbarkeit entdecken"
		lazyWarlockLocale.deDE.ACTION_TTS.funnel              = "Lebenslinie"
		lazyWarlockLocale.deDE.ACTION_TTS.paranoia            = "Paranoia"
		lazyWarlockLocale.deDE.ACTION_TTS.shadowWard          = "Schattenzauberschutz"
		lazyWarlockLocale.deDE.ACTION_TTS.soulLink            = "Seelenverbindung "
		
		lazyWarlockLocale.deDE.ACTION_TTS.taintedBlood        = "Besudeltes Blut"
		lazyWarlockLocale.deDE.ACTION_TTS.torment             = "Qual"
		
		lazyWarlockLocale.deDE.ACTION_TTS.createFire          = "Feuerstein herstellen"
		lazyWarlockLocale.deDE.ACTION_TTS.createGreaterFire   = "Feuerstein herstellen (groß)"
		lazyWarlockLocale.deDE.ACTION_TTS.createLesserFire    = "Feuerstein herstellen (gering)"
		lazyWarlockLocale.deDE.ACTION_TTS.createMajorFire     = "Feuerstein herstellen (erheblich)"
		
		lazyWarlockLocale.deDE.ACTION_TTS.createGreaterHealth = "Gesundheitsstein herstellen (groß)"
		lazyWarlockLocale.deDE.ACTION_TTS.createHealth        = "Gesundheitsstein herstellen"
		lazyWarlockLocale.deDE.ACTION_TTS.createLesserHealth  = "Gesundheitsstein herstellen (gering)"
		lazyWarlockLocale.deDE.ACTION_TTS.createMajorHealth   = "Gesundheitsstein herstellen (erheblich)"
		lazyWarlockLocale.deDE.ACTION_TTS.createMinorHealth   = "Gesundheitsstein herstellen"
		
		lazyWarlockLocale.deDE.ACTION_TTS.createGreaterSoul   = "Seelenstein herstellen (groß)"
		lazyWarlockLocale.deDE.ACTION_TTS.createLesserSoul    = "Seelenstein herstellen (gering)"
		lazyWarlockLocale.deDE.ACTION_TTS.createMajorSoul     = "Seelenstein herstellen (erheblich)"
		lazyWarlockLocale.deDE.ACTION_TTS.createMinorSoul     = "Seelenstein herstellen (schwach)"
		lazyWarlockLocale.deDE.ACTION_TTS.createSoul          = "Seelenstein herstellen"
		
		lazyWarlockLocale.deDE.ACTION_TTS.createGreaterSpell  = "Zauberstein herstellen (groß)"
		lazyWarlockLocale.deDE.ACTION_TTS.createMajorSpell    = "Zauberstein herstellen (erheblich)"
		lazyWarlockLocale.deDE.ACTION_TTS.createSpell         = "Zauberstein herstellen"
		
		lazyWarlockLocale.deDE.HEALTHSTONE                    = "Gesundheitsstein"
		lazyWarlockLocale.deDE.SOULSTONE                      = "herstellen"
		lazyWarlockLocale.deDE.FIRESTONE                      = "Feuerstein"
		
		elseif (locale == "frFR") then
		
		lazyWarlockLocale.frFR.ACTION_TTS.consumeShadows      = "Consumer les ombres"
		lazyWarlockLocale.frFR.ACTION_TTS.curseDoom           = "Effet Mal\195\169diction funeste"
		lazyWarlockLocale.frFR.ACTION_TTS.curseReckless       = "Mal\195\169diction de t\195\169m\195\169rit\195\169"
		lazyWarlockLocale.frFR.ACTION_TTS.demonArmor          = "Armure d\195\169moniaque"
		lazyWarlockLocale.frFR.ACTION_TTS.demonSkin           = "Peau de d\195\169mon"
		lazyWarlockLocale.frFR.ACTION_TTS.detectGreaterInvis  = "D\195\169tection de l'invisibilit\195\169 sup\195\169rieure"
		lazyWarlockLocale.frFR.ACTION_TTS.detectInvis         = "D\195\169tection de l'invisibilit\195\169"
		lazyWarlockLocale.frFR.ACTION_TTS.funnel              = "Captation de vie"
		lazyWarlockLocale.frFR.ACTION_TTS.paranoia            = "Parano\195\175a"
		lazyWarlockLocale.frFR.ACTION_TTS.shadowWard          = "Gardien de l'ombre"
		lazyWarlockLocale.frFR.ACTION_TTS.soulLink            = "Lien spirituel"
		
		lazyWarlockLocale.frFR.ACTION_TTS.createFire          = "Cr\195\169ation de Pierre de feu"
		lazyWarlockLocale.frFR.ACTION_TTS.createGreaterFire   = "Cr\195\169ation de Pierre de feu (sup\195\169rieure)"
		lazyWarlockLocale.frFR.ACTION_TTS.createLesserFire    = "Cr\195\169ation de Pierre de feu (inf\195\169rieure)"
		lazyWarlockLocale.frFR.ACTION_TTS.createMajorFire     = "Cr\195\169ation de Pierre de feu (majeure)"
		
		lazyWarlockLocale.frFR.ACTION_TTS.createGreaterHealth = "Cr\195\169ation de Pierre de soins (sup\195\169rieure)"
		lazyWarlockLocale.frFR.ACTION_TTS.createHealth        = "Cr\195\169ation de Pierre de soins"
		lazyWarlockLocale.frFR.ACTION_TTS.createLesserHealth  = "Cr\195\169ation de Pierre de soins (inf\195\169rieure)"
		lazyWarlockLocale.frFR.ACTION_TTS.createMajorHealth   = "Cr\195\169ation de Pierre de soins (majeure)"
		lazyWarlockLocale.frFR.ACTION_TTS.createMinorHealth   = "Cr\195\169ation de Pierre de soins (mineure)"
		
		lazyWarlockLocale.frFR.ACTION_TTS.createGreaterSoul   = "Cr\195\169ation de Pierre d'\195\162me (sup\195\169rieure)"
		lazyWarlockLocale.frFR.ACTION_TTS.createLesserSoul    = "Cr\195\169ation de Pierre d'\195\162me (inf\195\169rieure)"
		lazyWarlockLocale.frFR.ACTION_TTS.createMajorSoul     = "Cr\195\169ation de Pierre d'\195\162me (majeure)"
		lazyWarlockLocale.frFR.ACTION_TTS.createMinorSoul     = "Cr\195\169ation de Pierre d'\195\162me (mineure)"
		lazyWarlockLocale.frFR.ACTION_TTS.createSoul          = "Cr\195\169ation de Pierre d'\195\162me"
		
		lazyWarlockLocale.frFR.ACTION_TTS.createGreaterSpell  = "Cr\195\169ation de Pierre de sort (sup\195\169rieure)"
		lazyWarlockLocale.frFR.ACTION_TTS.createMajorSpell    = "Cr\195\169ation de Pierre de sort(majeure)"
		lazyWarlockLocale.frFR.ACTION_TTS.createSpell         = "Cr\195\169ation de Pierre de sort"
		
		lazyWarlockLocale.frFR.ACTION_TTS.taintedBlood        = "Corruption sanguine"
		lazyWarlockLocale.frFR.ACTION_TTS.torment             = "Tourment"
		
		lazyWarlockLocale.frFR.HEALTHSTONE                    = "Pierre de soin"
		lazyWarlockLocale.frFR.SOULSTONE                      = "Pierre d'\195\162me"
		lazyWarlockLocale.frFR.FIRESTONE                      = "Pierre de feu"

		elseif (locale == "zhCN") then
			
		lazyWarlockLocale.zhCN.ACTION_TTS.amplifyCurse        = "诅咒增幅"
		lazyWarlockLocale.zhCN.ACTION_TTS.banish              = "放逐术"
		lazyWarlockLocale.zhCN.ACTION_TTS.conflagrate         = "燃烧"
		lazyWarlockLocale.zhCN.ACTION_TTS.corruption          = "腐蚀术"
		lazyWarlockLocale.zhCN.ACTION_TTS.createFire          = "制造火焰石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createGreaterFire   = "制造强效火焰石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createLesserFire    = "制造次级火焰石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createMajorFire     = "制造特效火焰石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createGreaterHealth = "制造强效治疗石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createHealth        = "制造治疗石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createLesserHealth  = "制造次级治疗石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createMajorHealth   = "制造特效治疗石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createMinorHealth   = "制造初级治疗石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createGreaterSoul   = "制造强效灵魂石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createLesserSoul    = "制造次级灵魂石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createMajorSoul     = "制造特效灵魂石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createMinorSoul     = "制造初级灵魂石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createSoul          = "制造灵魂石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createGreaterSpell  = "制造强效法术石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createMajorSpell    = "制造特效法术石"
		lazyWarlockLocale.zhCN.ACTION_TTS.createSpell         = "制造法术石"
		lazyWarlockLocale.zhCN.ACTION_TTS.curseAgony          = "痛苦诅咒"
		lazyWarlockLocale.zhCN.ACTION_TTS.curseDoom           = "厄运诅咒"
		lazyWarlockLocale.zhCN.ACTION_TTS.curseElements       = "元素诅咒"
		lazyWarlockLocale.zhCN.ACTION_TTS.curseExhaustion     = "疲劳诅咒"
		lazyWarlockLocale.zhCN.ACTION_TTS.curseReckless       = "鲁莽诅咒"
		lazyWarlockLocale.zhCN.ACTION_TTS.curseShadow         = "暗影诅咒"
		lazyWarlockLocale.zhCN.ACTION_TTS.curseTongues        = "语言诅咒"
		lazyWarlockLocale.zhCN.ACTION_TTS.curseWeakness       = "虚弱诅咒"
		lazyWarlockLocale.zhCN.ACTION_TTS.darkPact            = "黑暗契约"
		lazyWarlockLocale.zhCN.ACTION_TTS.deathCoil           = "死亡缠绕"
		lazyWarlockLocale.zhCN.ACTION_TTS.demonArmor          = "魔甲术"
		lazyWarlockLocale.zhCN.ACTION_TTS.demonSacrifice      = "恶魔牺牲"
		lazyWarlockLocale.zhCN.ACTION_TTS.demonSkin           = "恶魔皮肤"
		lazyWarlockLocale.zhCN.ACTION_TTS.detectGreaterInvis  = "侦测强效隐形"
		lazyWarlockLocale.zhCN.ACTION_TTS.detectInvis         = "侦测隐形"
		lazyWarlockLocale.zhCN.ACTION_TTS.detectLesserInvis   = "侦测次级隐形"
		lazyWarlockLocale.zhCN.ACTION_TTS.drainLife           = "吸取生命"
		lazyWarlockLocale.zhCN.ACTION_TTS.drainMana           = "吸取法力"
		lazyWarlockLocale.zhCN.ACTION_TTS.drainSoul           = "吸取灵魂"
		lazyWarlockLocale.zhCN.ACTION_TTS.enslave             = "奴役恶魔"
		lazyWarlockLocale.zhCN.ACTION_TTS.fear                = "恐惧术"
		lazyWarlockLocale.zhCN.ACTION_TTS.felDomination       = "恶魔支配"
		lazyWarlockLocale.zhCN.ACTION_TTS.funnel              = "生命通道"
		lazyWarlockLocale.zhCN.ACTION_TTS.hellfire            = "地狱烈焰"
		lazyWarlockLocale.zhCN.ACTION_TTS.howl                = "恐惧嚎叫"
		lazyWarlockLocale.zhCN.ACTION_TTS.immolate            = "献祭"
		lazyWarlockLocale.zhCN.ACTION_TTS.inferno	          = "地狱火"
		lazyWarlockLocale.zhCN.ACTION_TTS.lifeTap             = "生命分流"
		lazyWarlockLocale.zhCN.ACTION_TTS.pact                = "黑暗契约"
		lazyWarlockLocale.zhCN.ACTION_TTS.pain                = "灼热之痛"
		lazyWarlockLocale.zhCN.ACTION_TTS.rainFire            = "火焰之雨"
		lazyWarlockLocale.zhCN.ACTION_TTS.senseDemons         = "感知恶魔"
		lazyWarlockLocale.zhCN.ACTION_TTS.shadowBolt          = "暗影箭"
		lazyWarlockLocale.zhCN.ACTION_TTS.shadowburn          = "暗影灼烧"
		lazyWarlockLocale.zhCN.ACTION_TTS.shadowWard          = "防护暗影结界"
		lazyWarlockLocale.zhCN.ACTION_TTS.siphon              = "生命虹吸"
		lazyWarlockLocale.zhCN.ACTION_TTS.soulFire            = "灵魂之火"
		lazyWarlockLocale.zhCN.ACTION_TTS.soulLink            = "灵魂链接"
		lazyWarlockLocale.zhCN.ACTION_TTS.summonDread         = "召唤恐惧战马"
		lazyWarlockLocale.zhCN.ACTION_TTS.spellLock           = "法术封锁"
		lazyWarlockLocale.zhCN.ACTION_TTS.summonFel           = "召唤地狱猎犬"
		lazyWarlockLocale.zhCN.ACTION_TTS.summonImp           = "召唤小鬼"
		lazyWarlockLocale.zhCN.ACTION_TTS.summonSteed         = "召唤地狱战马"
		lazyWarlockLocale.zhCN.ACTION_TTS.summonSuc           = "召唤魅魔"
		lazyWarlockLocale.zhCN.ACTION_TTS.summonVW            = "召唤虚空行者"
		lazyWarlockLocale.zhCN.ACTION_TTS.bloodPact           = "血之契印"
		lazyWarlockLocale.zhCN.ACTION_TTS.firebolt            = "火焰箭"
		lazyWarlockLocale.zhCN.ACTION_TTS.phaseShift          = "相位变换"
		lazyWarlockLocale.zhCN.ACTION_TTS.fireShield          = "火焰之盾"
		lazyWarlockLocale.zhCN.ACTION_TTS.consumeShadows      = "吞噬暗影"
		lazyWarlockLocale.zhCN.ACTION_TTS.sacrifice           = "牺牲"
		lazyWarlockLocale.zhCN.ACTION_TTS.suffering           = "受难"
		lazyWarlockLocale.zhCN.ACTION_TTS.torment             = "折磨"
		lazyWarlockLocale.zhCN.ACTION_TTS.lashPain            = "剧痛鞭笞"
		lazyWarlockLocale.zhCN.ACTION_TTS.lesserInvisibility  = "次级隐形术"
		lazyWarlockLocale.zhCN.ACTION_TTS.seduction           = "诱惑"
		lazyWarlockLocale.zhCN.ACTION_TTS.soothingKiss        = "安抚之吻"
		lazyWarlockLocale.zhCN.ACTION_TTS.taintedBlood        = "腐坏之血"
		lazyWarlockLocale.zhCN.ACTION_TTS.spellLock           = "法术封锁"
		lazyWarlockLocale.zhCN.ACTION_TTS.devourMagic         = "吞噬魔法"
		lazyWarlockLocale.zhCN.ACTION_TTS.paranoia            = "多疑"
		lazyWarlockLocale.zhCN.HEALTHSTONE                    = "治疗石"
		lazyWarlockLocale.zhCN.SOULSTONE                      = "灵魂石"
		lazyWarlockLocale.zhCN.FIRESTONE                      = "火焰石"
	
	end
end
