lazyShamanLoad.metadata:updateRevisionFromKeyword("$Revision: 474 $")

function lazyShamanLoad.LoadShamanLocalization(locale)
	
	lazyShamanLocale.enUS.ACTION_TTS.earthShock           = "Earth Shock"
	lazyShamanLocale.enUS.ACTION_TTS.flameShock           = "Flame Shock"
	lazyShamanLocale.enUS.ACTION_TTS.frostShock           = "Frost Shock"
	lazyShamanLocale.enUS.ACTION_TTS.rockbiter            = "Rockbiter Weapon"
	lazyShamanLocale.enUS.ACTION_TTS.flametongue          = "Flametongue Weapon"
	lazyShamanLocale.enUS.ACTION_TTS.frostbrand           = "Frostbrand Weapon"
	lazyShamanLocale.enUS.ACTION_TTS.windfury             = "Windfury Weapon"
	lazyShamanLocale.enUS.ACTION_TTS.chainHeal            = "Chain Heal"
	lazyShamanLocale.enUS.ACTION_TTS.chainLight           = "Chain Lightning"
	lazyShamanLocale.enUS.ACTION_TTS.cureDisease          = "Cure Disease"
	lazyShamanLocale.enUS.ACTION_TTS.curePoison           = "Cure Poison"
	lazyShamanLocale.enUS.ACTION_TTS.elemMastery          = "Elemental Mastery"
	lazyShamanLocale.enUS.ACTION_TTS.ghostWolf            = "Ghost Wolf"
	lazyShamanLocale.enUS.ACTION_TTS.heal                 = "Healing Wave"
	lazyShamanLocale.enUS.ACTION_TTS.lesserHeal           = "Lesser Healing Wave"
	lazyShamanLocale.enUS.ACTION_TTS.lightBolt            = "Lightning Bolt"
	lazyShamanLocale.enUS.ACTION_TTS.lightShield          = "Lightning Shield"
	lazyShamanLocale.enUS.ACTION_TTS.natureSwift          = "Nature's Swiftness"
	lazyShamanLocale.enUS.ACTION_TTS.purge                = "Purge"
	lazyShamanLocale.enUS.ACTION_TTS.stormstrike          = "Stormstrike"
	
	lazyShamanLocale.enUS.ACTION_TTS.diseaseTotem         = "Disease Cleansing Totem"
	lazyShamanLocale.enUS.ACTION_TTS.bindTotem            = "Earthbind Totem"
	lazyShamanLocale.enUS.ACTION_TTS.fireNovaTotem        = "Fire Nova Totem"
	lazyShamanLocale.enUS.ACTION_TTS.fireResistTotem      = "Fire Resistance Totem"
	lazyShamanLocale.enUS.ACTION_TTS.flameTotem           = "Flametongue Totem"
	lazyShamanLocale.enUS.ACTION_TTS.frostResistTotem     = "Frost Resistance Totem"
	lazyShamanLocale.enUS.ACTION_TTS.graceTotem           = "Grace of Air Totem"
	lazyShamanLocale.enUS.ACTION_TTS.groundingTotem       = "Grounding Totem"
	lazyShamanLocale.enUS.ACTION_TTS.hsTotem              = "Healing Stream Totem"
	lazyShamanLocale.enUS.ACTION_TTS.magmaTotem           = "Magma Totem"
	lazyShamanLocale.enUS.ACTION_TTS.msTotem              = "Mana Spring Totem"
	lazyShamanLocale.enUS.ACTION_TTS.mtTotem              = "Mana Tide Totem"
	lazyShamanLocale.enUS.ACTION_TTS.natureResistTotem    = "Nature Resistance Totem"
	lazyShamanLocale.enUS.ACTION_TTS.poisonTotem          = "Poison Cleansing Totem"
	lazyShamanLocale.enUS.ACTION_TTS.searingTotem         = "Searing Totem"
	lazyShamanLocale.enUS.ACTION_TTS.sentryTotem          = "Sentry Totem"
	lazyShamanLocale.enUS.ACTION_TTS.clawTotem            = "Stoneclaw Totem"
	lazyShamanLocale.enUS.ACTION_TTS.skinTotem            = "Stoneskin Totem"
	lazyShamanLocale.enUS.ACTION_TTS.strengthTotem        = "Strength of Earth Totem"
	lazyShamanLocale.enUS.ACTION_TTS.tranquilTotem        = "Tranquil Air Totem"
	lazyShamanLocale.enUS.ACTION_TTS.tremorTotem          = "Tremor Totem"
	lazyShamanLocale.enUS.ACTION_TTS.wfTotem              = "Windfury Totem"
	lazyShamanLocale.enUS.ACTION_TTS.windwallTotem        = "Windwall Totem"
	
	-- LazyShaman.lua
	SHAMAN_ADDON_LOADED = " loaded. Powered by "
	
	-- ParseShaman.lua
	function lazyShaman.CustomLocaleHelp() return [[<H2>Shaman Criteria:</H2>]] end
	
	if (locale == "ruRU") then
		
		lazyShamanLocale.ruRU.ACTION_TTS.earthShock           = "Земной шок"
		lazyShamanLocale.ruRU.ACTION_TTS.flameShock           = "Огненный шок"
		lazyShamanLocale.ruRU.ACTION_TTS.frostShock           = "Ледяной шок"
		lazyShamanLocale.ruRU.ACTION_TTS.rockbiter            = "Оружие Камнедробителя"
		lazyShamanLocale.ruRU.ACTION_TTS.flametongue          = "Оружие языка пламени"
		lazyShamanLocale.ruRU.ACTION_TTS.frostbrand           = "Оружие ледяного клейма"
		lazyShamanLocale.ruRU.ACTION_TTS.windfury             = "Оружие неистовства ветра"
		lazyShamanLocale.ruRU.ACTION_TTS.chainHeal            = "Цепное исцеление"
		lazyShamanLocale.ruRU.ACTION_TTS.chainLight           = "Цепная молния"
		lazyShamanLocale.ruRU.ACTION_TTS.cureDisease          = "Излечение болезни"
		lazyShamanLocale.ruRU.ACTION_TTS.curePoison           = "Выведение яда"
		lazyShamanLocale.ruRU.ACTION_TTS.elemMastery          = "Покорение стихий"
		lazyShamanLocale.ruRU.ACTION_TTS.ghostWolf            = "Призрачный волк"
		lazyShamanLocale.ruRU.ACTION_TTS.heal                 = "Волна исцеления"
		lazyShamanLocale.ruRU.ACTION_TTS.lesserHeal           = "Малая волна исцеления"
		lazyShamanLocale.ruRU.ACTION_TTS.lightBolt            = "Молния"
		lazyShamanLocale.ruRU.ACTION_TTS.lightShield          = "Щит молний"
		lazyShamanLocale.ruRU.ACTION_TTS.natureSwift          = "Природная стремительность"
		lazyShamanLocale.ruRU.ACTION_TTS.purge                = "Развеяние магии"
		lazyShamanLocale.ruRU.ACTION_TTS.stormstrike          = "Удар бури"
		
		lazyShamanLocale.ruRU.ACTION_TTS.diseaseTotem         = "Тотем очищения от болезней"
		lazyShamanLocale.ruRU.ACTION_TTS.bindTotem            = "Тотем оков земли"
		lazyShamanLocale.ruRU.ACTION_TTS.fireNovaTotem        = "Тотем кольца огня"
		lazyShamanLocale.ruRU.ACTION_TTS.fireResistTotem      = "Тотем защиты от огня"
		lazyShamanLocale.ruRU.ACTION_TTS.flameTotem           = "Тотем языка пламени"
		lazyShamanLocale.ruRU.ACTION_TTS.frostResistTotem     = "Тотем защиты от магии льда"
		lazyShamanLocale.ruRU.ACTION_TTS.graceTotem           = "Тотем легкости воздуха"
		lazyShamanLocale.ruRU.ACTION_TTS.groundingTotem       = "Тотем заземления"
		lazyShamanLocale.ruRU.ACTION_TTS.hsTotem              = "Тотем исцеляющего потока"
		lazyShamanLocale.ruRU.ACTION_TTS.magmaTotem           = "Тотем магмы"
		lazyShamanLocale.ruRU.ACTION_TTS.msTotem              = "Тотем источника маны"
		lazyShamanLocale.ruRU.ACTION_TTS.mtTotem              = "Тотем прилива маны"
		lazyShamanLocale.ruRU.ACTION_TTS.natureResistTotem    = "Тотем защиты от сил природы"
		lazyShamanLocale.ruRU.ACTION_TTS.poisonTotem          = "Тотем противоядия"
		lazyShamanLocale.ruRU.ACTION_TTS.searingTotem         = "Опаляющий тотем"
		lazyShamanLocale.ruRU.ACTION_TTS.sentryTotem          = "Сторожевой тотем"
		lazyShamanLocale.ruRU.ACTION_TTS.clawTotem            = "Тотем каменного когтя"
		lazyShamanLocale.ruRU.ACTION_TTS.skinTotem            = "Тотем каменной кожи"
		lazyShamanLocale.ruRU.ACTION_TTS.strengthTotem        = "Тотем силы земли"
		lazyShamanLocale.ruRU.ACTION_TTS.tranquilTotem        = "Тотем безветрия"
		lazyShamanLocale.ruRU.ACTION_TTS.tremorTotem          = "Тотем трепета"
		lazyShamanLocale.ruRU.ACTION_TTS.wfTotem              = "Тотем неистовства ветра"
		lazyShamanLocale.ruRU.ACTION_TTS.windwallTotem        = "Тотем стены ветра"
		
		-- LazyShaman.lua
		SHAMAN_ADDON_LOADED = " загружен. Работает от "
		
		-- ParseShaman.lua
		function lazyShaman.CustomLocaleHelp() return [[<H2>Критерии Шамана:</H2>]] end

		elseif (locale == "zhCN") then
		lazyShamanLocale.zhCN.ACTION_TTS.earthShock           = "地震术"
		lazyShamanLocale.zhCN.ACTION_TTS.flameShock           = "烈焰震击"
		lazyShamanLocale.zhCN.ACTION_TTS.frostShock           = "冰霜震击"
		lazyShamanLocale.zhCN.ACTION_TTS.rockbiter            = "石化武器"
		lazyShamanLocale.zhCN.ACTION_TTS.flametongue          = "火舌武器"
		lazyShamanLocale.zhCN.ACTION_TTS.frostbrand           = "冰封武器"
		lazyShamanLocale.zhCN.ACTION_TTS.windfury             = "风怒武器"
		lazyShamanLocale.zhCN.ACTION_TTS.chainHeal            = "治疗链"
		lazyShamanLocale.zhCN.ACTION_TTS.chainLight           = "闪电链"
		lazyShamanLocale.zhCN.ACTION_TTS.cureDisease          = "祛病术"
		lazyShamanLocale.zhCN.ACTION_TTS.curePoison           = "消毒术"
		lazyShamanLocale.zhCN.ACTION_TTS.elemMastery          = "元素掌握"
		lazyShamanLocale.zhCN.ACTION_TTS.ghostWolf            = "幽魂之狼"
		lazyShamanLocale.zhCN.ACTION_TTS.heal                 = "治疗波"
		lazyShamanLocale.zhCN.ACTION_TTS.lesserHeal           = "次级治疗波"
		lazyShamanLocale.zhCN.ACTION_TTS.lightBolt            = "闪电箭"
		lazyShamanLocale.zhCN.ACTION_TTS.lightShield          = "闪电之盾"
		lazyShamanLocale.zhCN.ACTION_TTS.natureSwift          = "自然迅捷"
		lazyShamanLocale.zhCN.ACTION_TTS.purge                = "净化术"
		lazyShamanLocale.zhCN.ACTION_TTS.stormstrike          = "风暴打击"
		
		lazyShamanLocale.zhCN.ACTION_TTS.diseaseTotem         = "祛病图腾"
		lazyShamanLocale.zhCN.ACTION_TTS.bindTotem            = "地缚图腾"
		lazyShamanLocale.zhCN.ACTION_TTS.fireNovaTotem        = "火焰新星图腾"
		lazyShamanLocale.zhCN.ACTION_TTS.fireResistTotem      = "抗火图腾"
		lazyShamanLocale.zhCN.ACTION_TTS.flameTotem           = "火舌图腾"
		lazyShamanLocale.zhCN.ACTION_TTS.frostResistTotem     = "抗寒图腾"
		lazyShamanLocale.zhCN.ACTION_TTS.graceTotem           = "风之优雅图腾"
		lazyShamanLocale.zhCN.ACTION_TTS.groundingTotem       = "根基图腾"
		lazyShamanLocale.zhCN.ACTION_TTS.hsTotem              = "治疗之泉图腾"
		lazyShamanLocale.zhCN.ACTION_TTS.magmaTotem           = "熔岩图腾"
		lazyShamanLocale.zhCN.ACTION_TTS.msTotem              = "法力之泉图腾"
		lazyShamanLocale.zhCN.ACTION_TTS.mtTotem              = "法力之潮图腾"
		lazyShamanLocale.zhCN.ACTION_TTS.natureResistTotem    = "自然抗性图腾"
		lazyShamanLocale.zhCN.ACTION_TTS.poisonTotem          = "清毒图腾"
		lazyShamanLocale.zhCN.ACTION_TTS.searingTotem         = "灼热图腾"
		lazyShamanLocale.zhCN.ACTION_TTS.sentryTotem          = "岗哨图腾"
		lazyShamanLocale.zhCN.ACTION_TTS.clawTotem            = "石爪图腾"
		lazyShamanLocale.zhCN.ACTION_TTS.skinTotem            = "石肤图腾"
		lazyShamanLocale.zhCN.ACTION_TTS.strengthTotem        = "大地之力图腾"
		lazyShamanLocale.zhCN.ACTION_TTS.tranquilTotem        = "宁静之风图腾"
		lazyShamanLocale.zhCN.ACTION_TTS.tremorTotem          = "战栗图腾"
		lazyShamanLocale.zhCN.ACTION_TTS.wfTotem              = "风怒图腾"
		lazyShamanLocale.zhCN.ACTION_TTS.windwallTotem        = "风墙图腾"
		
	end
end
